### ISSUE TITLE
Port from extension to browser snap-in

### ISSUE THREAD

**Issue by mindspank** [erikwett/DevTool#1]
What do you think of porting this into a browser extension for Chrome/Firefox?
It would decouple it from having to be an extension so you could potentially also use it for apps that has been published on the server.

I'd be happy to take a stab at it

**Comment by mindspank** [comment]
Clarification around "apps that has been published on the server." where you don't have edit access to add the extension that is :)

**Comment by erikwett** [comment]
Sounds like a good idea, go ahead! I would love to cooperate but have no experience in chrome extensions. Another benefit would be that it could work in mashup scenarios.

**Comment by mindspank** [comment]
So I was playing around with it, do you have tips on how to check if qlik is loaded on the page?
I could check for qvangularGlobal on the window object but if someone manually bootstraps our angular module on to the page...

Hmm, maybe that's an extreme edge-case we could live with :)

**Comment by erikwett** [comment]
No, I dont know of any better method, and I think it will be there in all
scenarios. But if you've got qlik in an iframe you would need to check that
too, guess you've thought of that..

**Comment by erikwett** [comment]
Fixed!
Check here:
https://chrome.google.com/webstore/detail/add-sense/bbiljflfafkaejgdebbnmcohpidgkejj
